### ISSUE TITLE
What values would you suggest to match ran­dom­Color.js?

### ISSUE THREAD

**Issue by LimeBlast** [jpmckinney/color-generator#2]
Hi, this looks like a cool library - I found it after searching for Ruby alternatives to [randomColour.js](https://randomcolor.llllll.li/), and think it could just hit the spot for what I need.. although I'm looking for a little guidance.

The readme says I can specify the `saturation` and `lightness` I want for generating the colours, and looking at what the randomColour.js readme says:

> ...ran­dom­Color pro­duces bright col­ors with a rea­son­ably high sat­u­ra­tion.

...suggests I should be able to set similar results from this library if I use the correct values - but I'm not sure which values I should be using when I instantiate the object.

I'm very new to playing with colours, so am actually a little confused by some of the terms used, so apologies if I'm asking silly questions.

Thank you.

**Comment by jpmckinney** [comment]
The values go from 0 to 1, so the highest saturation is 1.0. It's worth learning more about colorspaces, especially [HSV and HSL](https://en.wikipedia.org/wiki/HSL_and_HSV). In HSV, if you set `:value` to 1.0 you may still get a dark color (e.g. pure blue #0000ff is not light). So, I recommend using HSL with `:lightness`.

**Comment by LimeBlast** [comment]
Hi, thank you for your help. I spent a bit of time playing with it last night, and was quite happy with the following:

```ruby
ColorGenerator.new(saturation: 0.75, lightness: 0.4)
```
