### ISSUE TITLE
Error in rgb_from_hsl_or_hsv algorithm

### ISSUE THREAD

**Issue by fbuys** [jpmckinney/color-generator#6]
I think there might be an error in the link algorithm:
https://github.com/jpmckinney/color-generator/blob/e4ffecf799ec475878ed34533f3d6dc7b4ed0362/lib/color-generator.rb#L98

From wikipedia it seems like we should divide by 60, `h_prime = h / 60`.

Is this an error or am I mistaken and there is a valid reason we multiply here instead?

![image](https://user-images.githubusercontent.com/3785596/191261773-2bb08f78-28d6-489d-9a5c-c54581f0c8a2.png)

**Comment by jpmckinney** [comment]
In the code, h is 0-1. On Wikipedia (today, was different when written), h is 0-360. 360 / 60 = 1 * 6.
