### ISSUE TITLE
I wonder why 0.61 and not 2.4

### ISSUE THREAD

**Issue by Nakilon** [jpmckinney/color-generator#7]
https://en.wikipedia.org/wiki/Golden_angle

**Comment by jpmckinney** [comment]
Golden ratio not golden angle. And we take 1 / ratio. https://en.m.wikipedia.org/wiki/Golden_ratio

**Comment by Nakilon** [comment]
Aren't we dividing Hue circle? -- that's what golden angle is for.

**Comment by jpmckinney** [comment]
You can test the code... It produces the desired result. If you can show differently, I'll take a look!
